import json

QUOTE_MAP = {
    "The other side shall be heard as well.": "Seneca",
    "The greatest wealth is a poverty of desires.": "Seneca",
    "Things stand outside of us, themselves by themselves, neither knowing anything of themselves nor expressing any judgment.": "Marcus Aurelius",
    "Leisure without books is death, and burial of a man alive.": "Seneca",
    "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.": "Helen Keller",
    "Whatever happens to you has been waiting to happen since the beginning of time.": "Marcus Aurelius",
    "It is a rough road that leads to the heights of greatness.": "Seneca",
    "No man is free who is not master of himself.": "Epictetus",
    "Be tolerant with others and strict with yourself.": "Marcus Aurelius",
    "The key is to keep company only with people who uplift you, whose presence calls forth your best.": "Epictetus",
    "The part of life we really live is small.": "Seneca",
    "Demand not that things happen as you wish, but wish them to happen as they do, and you will go on well.": "Epictetus",
    "It is better to conquer our grief than to deceive it.": "Seneca",
    "This is the mark of perfection of character—to spend each day as if it were your last, without frenzy, laziness, or any pretending.": "Marcus Aurelius",
    "We don’t get to choose what happens to us, but we can always choose how we feel about it.": "Stoic Philosophy",
    "True happiness is to enjoy the present, without anxious dependence upon the future.": "Seneca",
    "Hugs are like boomerangs – you get them back right away.": "Bil Keane",
    "The things you think about determine the quality of your mind.": "Marcus Aurelius",
    "Sometimes even to live is an act of courage.": "Seneca",
    "You are a little soul carrying around a corpse.": "Epictetus",
    "That man lives badly who does not know how to die well.": "Seneca",
    "Ignorance is the cause of fear.": "Seneca",
    "Where the head goes, the body follows.": "Ryan Holiday",
    "There is no easy way from the earth to the stars.": "Seneca",
    "The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.": "Marcus Aurelius",
    "Those who have subdued their ego understand that it doesn’t degrade you when others treat you poorly; it degrades them.": "Ryan Holiday",
    "Try to enjoy the great festival of life.": "Epictetus",
    "A gift consists not in what is done or given, but in the intention of the giver or doer.": "Seneca",
    "Anger always outlasts hurt. Best to take the opposite course.": "Seneca",
    "We should always be asking ourselves - is this something that is, or is not, in my control?": "Epictetus",
    "Any person capable of angering you becomes your master; he can anger you only when you permit yourself to be disturbed by him.": "Epictetus",
    "Begin at once to live, and count each separate day as a separate life.": "Seneca",
    "Nothing is more honorable than a grateful heart.": "Seneca",
    "The wise man will live as long as he ought, not as long as he can.": "Seneca",
    "I am not born for one corner; the whole world is my native land.": "Seneca",
    "Love is not consolation. It is light.": "Friedrich Nietzsche",
    "Never make someone a priority when all you are to them is an option.": "Maya Angelou",
    "I shut my eyes in order to see.": "Paul Gauguin",
    "Reflect upon your present blessings—of which every man has many—not on your past misfortunes, of which all men have some.": "Charles Dickens",
    "By failing to prepare, you are preparing to fail.": "Benjamin Franklin",
    "Everything terrible is something that needs our love.": "Rainer Maria Rilke",
    "Life moves pretty fast. If you don’t stop and look around once in a while, you could miss it.": "Ferris Bueller",
    "The inner fire is the most important thing mankind possesses.": "Edith Södergran",
    "Where there is no hope, it is incumbent on us to invent it.": "Albert Camus",
    "Life can only be understood backwards; but it must be lived forwards.": "Søren Kierkegaard",
    "Falling is one of the ways of moving.": "Ocean Vuong",
    "Either write something worth reading or do something worth writing.": "Benjamin Franklin",
    "This is the miracle that happens every time to those who really love: the more they give, the more they possess.": "Rainer Maria Rilke",
    "True love begins when nothing is looked for in return.": "Antoine de Saint-Exupéry",
    "The most important decision you make is to be in a good mood.": "Voltaire",
    "Where there's life there's hope.": "Cicero",
    "It always seems impossible until it’s done.": "Nelson Mandela",
    "Life is a journey, and if you fall in love with the journey, you will be in love forever.": "Peter Hagerty",
    "Pleasure in the job puts perfection in the work.": "Aristotle",
    "However difficult life may seem, there is always something you can do and succeed at.": "Stephen Hawking",
    "We need to remember what's important in life: friends, waffles, work.": "Leslie Knope",
    "Truth is so rare, it is delightful to tell it.": "Emily Dickinson",
    "You can’t cross the sea merely by standing and staring at the water.": "Rabindranath Tagore",
    "Absolutely unmixed attention is prayer.": "Simone Weil",
    "I am not afraid of storms for I am learning how to sail my ship.": "Louisa May Alcott",
    "Success isn’t about how your life looks to others. It’s about how it feels to you.": "Michelle Obama",
    "Never confuse a single defeat with a final defeat.": "F. Scott Fitzgerald",
    "Your sacred space is where you can find yourself over and over again.": "Joseph Campbell",
    "People who deny the existence of dragons are often eaten by dragons. From within.": "Ursula K. Le Guin",
    "Love unlocks doors and opens windows that weren't even there before.": "Mignon McLaughlin",
    "I am grateful for what I am and have. My thanksgiving is perpetual.": "Henry David Thoreau",
    "What we really need is to realize how little we really need.": "Seneca",
    "You can make anything by writing.": "C.S. Lewis",
    "There is no greater agony than bearing an untold story inside you.": "Maya Angelou",
    "If you tell the truth, you don't have to remember anything.": "Mark Twain",
    "There is the strange power we have of changing facts by the force of the imagination.": "Virginia Woolf",
    "Well done is better than well said.": "Benjamin Franklin",
    "Try to be a rainbow in someone’s cloud.": "Maya Angelou",
    "Procrastination is the thief of time, collar him.": "Charles Dickens",
    "You shall know the truth and the truth shall make you mad.": "Aldous Huxley",
    "I can, therefore I am": "Simone Weil",
    "This will be our reply to violence: to make music more intensely, more beautifully, more devotedly than ever before.": "Leonard Bernstein",
    "With the new day comes new strength and new thoughts.": "Eleanor Roosevelt",
    "You don’t need more to be happy, you need less distraction from what truly matters.": "Maxime Lagacé",
    "The scariest moment is always just before you start.": "Stephen King",
    "Courage is found in unlikely places.": "J.R.R. Tolkien",
    "In true love, you attain freedom.": "Thich Nhat Hanh",
    "There are many ways to be free. One of them is to transcend reality by imagination.": "Anaïs Nin",
    "A single act of kindness throws out roots in all directions, and the roots spring up and make new trees.": "Amelia Earhart",
    "Truth is a matter of the imagination.": "Ursula K. Le Guin",
    "We’re all mad here.": "Lewis Carroll",
    "True love stories never have endings.": "Richard Bach",
    "Stories of imagination tend to upset those without one.": "Terry Pratchett",
    "When you reach the end of your rope, tie a knot in it and hang on.": "Franklin D. Roosevelt",
    "The world of reality has its limits; the world of imagination is boundless.": "Jean-Jacques Rousseau",
    "Perseverance and spirit have done wonders in all ages.": "George Washington",
    "The antidote for fifty enemies is one friend.": "Aristotle",
    "Shut your eyes and see.": "James Joyce",
    "It's as much fun to scare as to be scared.": "Vincent Price",
    "The greatest weapon against stress is our ability to choose one thought over another.": "William James",
    "Do the hard jobs first. The easy jobs will take care of themselves.": "Dale Carnegie",
    "We will fail when we fail to try.": "Rosa Parks",
    "The only way to do it is to do it.": "Merce Cunningham",
    "Adventure is not outside man; it is within.": "George Eliot",
    "Happiness is not a goal; it is a by-product of a life well-lived.": "Eleanor Roosevelt",
    "Let us be grateful to people who make us happy; they are the charming gardeners who make our souls blossom.": "Marcel Proust",
    "I don't like work--no man does--but I like what is in the work--the chance to find yourself.": "Joseph Conrad",
    "Life did not intend to make us perfect. Whoever is perfect belongs in a museum.": "Erich Maria Remarque",
    "I am certain of nothing but the holiness of the heart’s affections, and the truth of imagination.": "John Keats",
    "Stories do not end.": "Anaïs Nin",
    "The plan is to fan this spark into a flame.": "Hamilton",
    "Each of us is responsible for everything and to every human being.": "Simone de Beauvoir",
    "If they don’t give you a seat at the table, bring a folding chair.": "Shirley Chisholm",
    "A wonderful fact to reflect upon, that every human creature is constituted to be that profound secret and mystery to every other.": "Charles Dickens",
    "I attribute my success to this – I never gave or took any excuse.": "Florence Nightingale",
    "Curiouser and curiouser!": "Lewis Carroll",
    "Self-knowledge is no guarantee of happiness, but it is on the side of happiness and can supply the courage to fight for it.": "Simone de Beauvoir",
    "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.": "Albus Dumbledore",
    "Life is a shipwreck, but we must not forget to sing in the lifeboats.": "Voltaire",
    "Not until we are lost do we begin to understand ourselves.": "Henry David Thoreau",
    "I believe one writes because one has to create a world in which one can live.": "Anaïs Nin",
    "I don’t believe you have to be better than everybody else. I believe you have to be better than you ever thought you could be.": "Ken Venturi",
    "Keep your eyes on the stars, and your feet on the ground.": "Theodore Roosevelt",
    "The things you do for yourself are gone when you are gone, but the things you do for others remain as your legacy.": "Kalu Ndukwe Kalu",
    "We realize the importance of our voices only when we are silenced.": "Malala Yousafzai",
    "How hurtful it can be to deny one's true self and live a life of lies just to appease others.": "June Ahern",
    "Anxiety is the dizziness of freedom.": "Søren Kierkegaard",
    "The big question is whether you are going to be able to say a hearty yes to your adventure.": "Joseph Campbell",
    "To be creative means to be in love with life.": "Osho",
    "Laughter is the language of the soul.": "Pablo Neruda",
    "Imagination is the beginning of creation.": "George Bernard Shaw",
    "It is not enough to be busy; so are the ants. The question is: What are we busy about?": "Henry David Thoreau",
    "The only place where success comes before work is in the dictionary.": "Vidal Sassoon",
    "Think for yourself and let others enjoy the privilege of doing so too.": "Voltaire",
    "We don’t ask to be eternal beings. We only ask that things do not lose all their meaning.": "Antoine de Saint-Exupéry",
    "Don’t die without embracing the daring adventure your life was meant to be.": "Steve Pavlina",
    "You must go on adventures to find out where you truly belong": "Sue Fitzmaurice",
    "Love of beauty is taste. The creation of beauty is art.": "Ralph Waldo Emerson",
    "There are things known and there are things unknown, and in between are the doors of perception.": "Aldous Huxley",
    "Those who don't believe in magic will never find it.": "Roald Dahl",
    "There is a crack in everything, that’s how the light gets in.": "Leonard Cohen",
    "Tell me and I forget, teach me and I may remember, involve me and I learn.": "Benjamin Franklin",
    "It is not joy that makes us grateful; it is gratitude that makes us joyful.": "David Steindl-Rast",
    "We tend to forget that happiness doesn’t come as a result of getting something we don’t have, but rather of recognizing and appreciating what we do have.": "Frederick Keonig",
    "How very little can be done under the spirit of fear.": "Florence Nightingale",
    "Constantly talking isn’t necessarily communicating.": "Charlie Kaufman",
    "Happiness is a state of activity.": "Aristotle",
    "The soul always knows what to do to heal itself.": "Michelangelo",
    "There is nothing in the world so irresistibly contagious as laughter and good humor.": "Charles Dickens",
    "If you want peace, stop fighting.": "Ryūnosuke Akutagawa",
    "Attention is the rarest and purest form of generosity.": "Simone Weil",
    "Success is only meaningful and enjoyable if it feels like your own.": "Unknown",
    "Set your goals high, and don’t stop till you get there.": "Bo Jackson",
    "Nobody likes a clown at midnight.": "Stephen King",
    "Imagination is the only weapon in the war against reality.": "Lewis Carroll",
    "Have enough courage to trust love one more time and always one more time.": "Maya Angelou",
    "Someday is not a day of the week.": "Janet Dailey",
    "Give a man a fire and he's warm for a day, but set fire to him and he's warm for the rest of his life.": "Terry Pratchett",
    "Be the person your dog thinks you are.": "C.J. Frick",
    "As soon as you trust yourself, you will know how to live.": "Johann Wolfgang von Goethe",
    "The joy we feel has little to do with the circumstances of our lives and everything to do with the focus of our lives.": "Russell M. Nelson",
    "Within you, there is a stillness and a sanctuary to which you can retreat at any time and be yourself.": "Hermann Hesse",
    "Our truest life is when we are in dreams awake.": "Henry David Thoreau",
    "When you’ve worked hard, and done well, and walked through that doorway of opportunity, you do not slam it shut behind you.": "Michelle Obama",
    "When you are present, you can allow the mind to be as it is without getting entangled in it.": "Eckhart Tolle",
    "Every artist was first an amateur.": "Ralph Waldo Emerson",
    "Compassion directed toward oneself is true humility.": "Simone Weil",
    "The only thing we never get enough of is love; and the only thing we never give enough of is love.": "Henry Miller",
    "We must accept finite disappointment, but never lose infinite hope.": "Martin Luther King, Jr.",
    "Rules for happiness: something to do, someone to love, something to hope for.": "Immanuel Kant",
    "Real loss is only possible when you love something more than you love yourself.": "Robin Williams",
    "You can easily judge the character of a man by how he treats those who can do nothing for him.": "Malcolm S. Forbes",
    "Courage is not the absence of fear, but rather the assessment that something else is more important than fear.": "Franklin D. Roosevelt",
    "Either you run the day, or the day runs you.": "Jim Rohn",
    "The desire to reach for the stars is ambitious. The desire to reach hearts is wise.": "Maya Angelou",
    "Education is what remains after one has forgotten what one has learned in school.": "Albert Einstein",
    "Instead of trying to make your life perfect, give yourself the freedom to make it an adventure.": "Drew Barrymore",
    "To practice any art, no matter how well or badly, is a way to make your soul grow. So do it.": "Kurt Vonnegut",
    "You’ll never find peace of mind until you listen to your heart.": "George Michael",
    "Dare to think!": "Immanuel Kant",
    "Blessed are the hearts that can bend; they shall never be broken.": "Albert Camus",
    "If I can stop one heart from breaking, I shall not live in vain.": "Emily Dickinson",
    "There’s no place like home.": "L. Frank Baum",
    "If you spend too much time thinking about a thing, you'll never get it done.": "Bruce Lee",
    "The sun is a daily reminder that we too can rise again from the darkness, that we too can shine our own light.": "S. Ajna",
    "Think... of the world you carry within you.": "Rainer Maria Rilke",
    "Friendship... is not something you learn in school. But if you haven't learned the meaning of friendship, you really haven't learned anything.": "Muhammad Ali",
    "Courage, dear heart.": "C.S. Lewis",
    "Start where you are. Use what you have. Do what you can.": "Arthur Ashe",
    "Do not judge me by my successes, judge me by how many times I fell down and got back up again.": "Nelson Mandela",
    "We are all connected; To each other, biologically. To the earth, chemically. To the rest of the universe atomically.": "Neil deGrasse Tyson",
    "How wrong is it for a woman to expect the man to build the world she wants, rather than to create it herself?": "Anaïs Nin",
    "Mistakes are the portals of discovery.": "James Joyce",
    "Perseverance is not a long race; it is many short races one after the other.": "Walter Elliot",
    "Failure is an important part of your growth and developing resilience. Don’t be afraid to fail.": "Michelle Obama",
    "I would rather walk with a friend in the dark, than alone in the light.": "Helen Keller",
    "Do not wait; the time will never be ‘just right.’": "Napoleon Hill",
    "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.": "Lao Tzu",
    "Real change, enduring change, happens one step at a time.": "Ruth Bader Ginsburg",
    "An artist discovers his genius the day he dares not to please.": "André Gide",
    "A friend is, as it were, a second self.": "Cicero",
    "Change alone is eternal, perpetual, immortal.": "Arthur Schopenhauer",
    "When it comes to luck, you make your own.": "Bruce Springsteen",
    "Happiness depends upon ourselves.": "Aristotle",
    "Till I loved I never lived.": "Emily Dickinson",
    "One's life has value so long as one attributes value to the life of others.": "Simone de Beauvoir",
    "The world is but a canvas to our imagination.": "Henry David Thoreau",
    "Enjoy when you can, and endure when you must.": "Johann Wolfgang von Goethe",
    "Magic is believing in yourself, if you can do that, you can make anything happen.": "Johann Wolfgang von Goethe",
    "Remember this, whoever you are, however you are, you are equally valid, equally justified and equally beautiful.": "Unknown",
    "One must still have chaos in oneself to be able to give birth to a dancing star.": "Friedrich Nietzsche",
    "Learning is an ornament in prosperity, a refuge in adversity, and a provision in old age.": "Aristotle",
    "The most creative act you will ever undertake is the act of creating yourself.": "Deepak Chopra",
    "There is no end to the adventures that we can have if only we seek them with our eyes open.": "Jawaharlal Nehru",
    "Not all those who wander are lost.": "J.R.R. Tolkien",
    "The more you know yourself, the more you seek inner peace.": "Unknown",
    "You can’t wait for inspiration. You have to go after it with a club.": "Jack London",
    "A good laugh is sunshine in the house.": "William Makepeace Thackeray",
    "Do not fear to be eccentric in opinion, for every opinion now accepted was once eccentric.": "Bertrand Russell",
    "Remember to look up at the stars and not down at your feet.": "Stephen Hawking",
    "To me, the moral of the story was that there will always be hurdles in life, but if you want to achieve a goal, you must continue.": "Malala Yousafzai",
    "If you want something new, you have to stop doing something old.": "Unknown",
    "The greatest thing in this world is not so much where we stand as in what direction we are moving.": "Johann Wolfgang von Goethe",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.": "Winston Churchill",
    "The spiritual journey is the unlearning of fear and the acceptance of love.": "Marianne Williamson",
    "All that we see or seem is but a dream within a dream.": "Edgar Allan Poe",
    "We loved with a love that was more than love.": "Edgar Allan Poe",
    "There is no exquisite beauty… without some strangeness in the proportion.": "Edgar Allan Poe",
    "Words have no power to impress the mind without the exquisite horror of their reality.": "Edgar Allan Poe",
    "Believe only half of what you see and nothing that you hear.": "Edgar Allan Poe",
    "I became insane, with long intervals of horrible sanity.": "Edgar Allan Poe",
    "It is the mark of an educated mind to be able to entertain a thought without accepting it.": "Aristotle",
    "Knowing yourself is the beginning of all wisdom.": "Aristotle",
    "Patience is bitter, but its fruit is sweet.": "Aristotle",
    "The more you know, the more you know you don't know.": "Aristotle",
    "You will never do anything in this world without courage.": "Aristotle",
    "The trouble with the world is that the stupid are cocksure and the intelligent are full of doubt.": "Bertrand Russell",
    "I would never die for my beliefs because I might be wrong.": "Bertrand Russell",
    "The good life is one inspired by love and guided by knowledge.": "Bertrand Russell",
    "The only thing that will redeem mankind is cooperation.": "Bertrand Russell",
    "Fear is the main source of superstition, and one of the main sources of cruelty.": "Bertrand Russell",
    "A life without adventure is likely to be unsatisfying, but a life in which adventure is allowed to take whatever form it will is sure to be short.": "Bertrand Russell",
    "Imagination is the soul’s happiest retreat.": "Unknown",
    "Nothing shows a man's character more than what he laughs at.": "Johann Wolfgang von Goethe",
    "Art is not a mirror held up to reality but a hammer with which to shape it.": "Bertolt Brecht",
    "I was smiling yesterday, I am smiling today and I will smile tomorrow.": "Santosh Kalwar",
    "One's destination is never a place, but a new way of seeing things.": "Henry Miller",
    "To invent, you need a good imagination and a pile of junk.": "Thomas Edison",
    "Before anything else, preparation is the key to success.": "Alexander Graham Bell",
    "If you don’t get out there and define yourself, you’ll be quickly and inaccurately defined by others.": "Michelle Obama",
    "The biggest adventure you can ever take is to live the life of your dreams.": "Oprah Winfrey",
    "It is never too late to be what you might have been.": "George Eliot",
    "But eyes are blind. You have to look with the heart.": "Antoine de Saint-Exupéry",
    "Never measure the height of a mountain until you reach the top. Then you will see how low it was.": "Dag Hammarskjöld",
    "The secret of genius is to carry the spirit of the child into old age, which means never losing your enthusiasm.": "Aldous Huxley",
    "No work is insignificant. All labor that uplifts humanity has dignity and importance and should be undertaken with painstaking excellence.": "Martin Luther King, Jr.",
    "Lost time is never found again.": "Benjamin Franklin",
    "True happiness comes from the joy of deeds well done, the zest of creating things new.": "Antoine de Saint-Exupéry",
    "The arts are not a way to make a living. They are a very human way of making life more bearable.": "Kurt Vonnegut",
    "It's your outlook on life that counts. If you take yourself lightly and don't take yourself too seriously, pretty soon you can find the humor in our everyday lives.": "Betty White",
    "Be happy for this moment. This moment is your life.": "Omar Khayyam",
    "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.": "Maya Angelou",
    "If I cannot do great things, I can do small things in a great way.": "Martin Luther King, Jr.",
    "All things are difficult before they are easy.": "Thomas Fuller",
    "When I dare to be powerful — to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.": "Audre Lorde",
    "You're only given a spark of madness. You musn’t lose it.": "Robin Williams",
    "Unable are the loved to die. For love is immortality.": "Emily Dickinson",
    "If there’s one thing I’ve learned in life, it’s the power of using your voice.": "Michelle Obama",
    "He who has overcome his fears will truly be free.": "Aristotle",
    "It’s hard to beat a person who never gives up.": "Babe Ruth",
    "Wars not make one great": "Yoda",
    "Happiness is the secret to all beauty. There is no beauty without happiness.": "Christian Dior",
    "Find ecstasy in life; the mere sense of living is joy enough.": "Emily Dickinson",
    "If you’ve never eaten while crying you don’t know what life tastes like": "Johann Wolfgang von Goethe",
    "Set peace of mind as your highest goal, and organize your life around it.": "Brian Tracy",
    "Our greatest weakness lies in giving up.": "Thomas Edison",
    "The best way to have a good idea is to have lots of ideas.": "Linus Pauling",
    "You can't make decisions based on fear and the possibility of what might happen.": "Michelle Obama",
    "Somewhere between the bottom of the climb and the summit is the answer to the mystery why we climb.": "Greg Child",
    "No opinion is worth burning your neighbor for.": "Voltaire",
    "That's what I consider true generosity: You give your all, and yet you always feel as if it costs you nothing.": "Simone de Beauvoir",
    "Do or do not. There is no try.": "Yoda",
    "Work gives you meaning and purpose and life is empty without it.": "Stephen Hawking",
    "Your story is what you have, what you will always have. It is something to own.": "Michelle Obama",
    "Without ambition one starts nothing. Without work one finishes nothing.": "Ralph Waldo Emerson",
    "You cannot have a positive life and a negative mind.": "Joyce Meyer",
    "The aim of life is to live, and to live means to be aware, joyously, drunkenly, serenely, divinely aware.": "Henry Miller",
    "Creativity is not a talent. It is a way of operating.": "John Cleese",
    "Never close your lips to those whom you have already opened your heart.": "Charles Dickens",
    "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.": "Stephen King",
    "So whatever you want to do, just do it... Making a damn fool of yourself is absolutely essential.": "Gloria Steinem",
    "To do the useful thing, to say the courageous thing, to contemplate the beautiful thing: that is enough for one man’s life.": "T.S. Eliot",
    "A man sees in the world what he carries in his heart.": "Johann Wolfgang von Goethe",
    "Inspiration usually comes during work, rather than before it.": "Madeleine L'Engle",
    "Plans are nothing; planning is everything.": "Dwight D. Eisenhower",
    "There is only one corner of the universe you can be certain of improving, and that’s your own self.": "Aldous Huxley",
    "There is no limit to what we, as women, can accomplish.": "Michelle Obama",
    "Love is a canvas furnished by nature and embroidered by imagination.": "Voltaire",
    "You can only come to the morning through the shadows.": "J.R.R. Tolkien",
    "Going in one more round when you don’t think you can. That’s what makes all the difference in your life.": "Rocky Balboa",
    "People have stars, but they aren't the same.": "Antoine de Saint-Exupéry",
    "Somewhere, something incredible is waiting to be known.": "Carl Sagan",
    "Doors are for people with no imagination.": "Derek Landy",
    "If you’re not prepared to be wrong, you'll never come up with anything original.": "Ken Robinson",
    "One is not born, but rather becomes, a woman.": "Simone de Beauvoir",
    "The only thing we have to fear is fear itself.": "Franklin D. Roosevelt",
    "Our heart always transcends us.": "Rainer Maria Rilke",
    "I wish that every human life might be pure transparent freedom.": "Simone de Beauvoir",
    "Let life happen to you. Believe me: life is in the right, always.": "Rainer Maria Rilke",
    "Action may not always bring happiness, but there is no happiness without action.": "Benjamin Disraeli",
    "Your mind is for having ideas, not holding them.": "David Allen",
    "The Heart wants what it wants - or else it does not care.": "Emily Dickinson",
    "To think is easy. To act is hard. But the hardest thing in the world is to act in accordance with your thinking.": "Johann Wolfgang von Goethe",
    "Daring ideas are like chessmen moved forward.": "Johann Wolfgang von Goethe",
    "You can cut all the flowers but you cannot keep Spring from coming.": "Pablo Neruda",
    "Do not whine... Do not complain. Work harder. Spend more time alone.": "Joan Didion",
    "Forgiveness is not an occasional act, it is a constant attitude.": "Martin Luther King, Jr.",
    "Every day it gets a little easier…": "BoJack Horseman",
    "Live, travel, adventure, bless, and don't be sorry.": "Jack Kerouac",
    "Life shrinks or expands in proportion to one's courage.": "Anaïs Nin",
    "Gratitude unlocks the fullness of life.": "Melody Beattie",
    "To die will be an awfully big adventure.": "J.M. Barrie",
    "Knowing is not enough; we must apply. Willing is not enough; we must do.": "Johann Wolfgang von Goethe",
    "Don’t count the days, make the days count.": "Muhammad Ali",
    "If you fall in love with the imagination, you understand that it is a free spirit.": "Alice Sebold",
    "Negativity is the enemy of creativity.": "David Lynch",
    "The heart has its reasons which reason knows nothing of.": "Blaise Pascal",
    "The energy of the mind is the essence of life.": "Aristotle",
    "Love doesn’t make the world go round. Love is what makes the ride worthwhile.": "Franklin P. Jones",
    "If you fell down yesterday, stand up today.": "H.G. Wells",
    "Don't be satisfied with stories, how things have gone with others. Unfold your own myth.": "Rumi",
    "The supreme question about a work of art is out of how deep a life does it spring.": "James Joyce",
    "Your writing is never as good as you hoped; but never as bad as you feared.": "Bertrand Russell",
    "If we were meant to stay in one place, we would have roots instead of feet.": "Rachel Wolchin",
    "Happiness radiates like the fragrance from a flower and draws all good things towards you.": "Maharishi Mahesh Yogi",
    "They say: Think twice before you jump. I say: Jump first and then think as much as you want!": "Osho",
    "Destiny is what you are supposed to do in life. Fate is what kicks you in the ass to make you do it.": "Henry Miller",
    "We must not wish for the disappearance of our troubles but for the grace to transform them.": "Simone Weil",
    "Faithless is he that says farewell when the road darkens.": "J.R.R. Tolkien",
    "But it is one thing to read about dragons and another to meet them.": "Ursula K. Le Guin",
    "The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair.": "J.R.R. Tolkien",
    "You don’t have to control your thoughts. You just have to stop letting them control you.": "Dan Millman",
    "It is not the strength of the body that counts, but the strength of the spirit.": "J.R.R. Tolkien",
    "Joy is what happens to us when we allow ourselves to recognize how good things really are.": "Marianne Williamson",
    "It's not enough to be nice in life. You've got to have nerve.": "Georgia O'Keeffe",
    "Every traveler has a home of his own, and he learns to appreciate it the more from his wandering.": "Charles Dickens",
    "A man should hear a little music, read a little poetry, and see a fine picture every day.": "Johann Wolfgang von Goethe",
    "You need imagination in order to imagine a future that doesn’t exist.": "Azar Nafisi",
    "Nothing is less productive than to make more efficient what should not be done at all.": "Peter Drucker",
    "If we go down into ourselves, we find that we possess exactly what we desire.": "Simone Weil",
    "Through discipline comes freedom.": "Aristotle",
    "Real generosity towards the future lies in giving all to the present.": "Albert Camus",
    "Life belongs to the living, and he who lives must be prepared for changes.": "Johann Wolfgang von Goethe",
    "What we do in life echoes in eternity.": "Maximus Decimus Meridius",
    "Have a heart that never hardens, and a temper that never tires, and a touch that never hurts.": "Charles Dickens",
    "Sometimes even the wisest of men and machines can be in error.": "Obi-Wan Kenobi",
    "Well-behaved women seldom make history.": "Laurel Thatcher Ulrich",
    "Science is not only compatible with spirituality; it is a profound source of spirituality.": "Carl Sagan",
    "Fate is like a strange, unpopular restaurant filled with odd little waiters.": "Lemony Snicket",
    "Excellence is never an accident.": "Aristotle",
    "The big secret in life is that there is no big secret.": "Oprah Winfrey",
    "You simply have to put one foot in front of the other and keep going.": "George Lucas",
    "Creativity is inventing, experimenting, growing, taking risks, breaking rules, making mistakes, and having fun.": "Mary Lou Cook",
    "If you can't fly then run, if you can't run then walk...": "Martin Luther King, Jr.",
    "You can’t stay in your corner of the Forest waiting for others to come to you.": "A.A. Milne",
    "Go then, there are other worlds than these.": "Stephen King",
}

with open('data/stoic-content.json', 'r') as f:
    data = json.load(f)

updated_count = 0
for entry in data:
    quote = entry.get('quote', '').strip()
    # Fuzzy match or exact match
    # We will try exact first, then "startswith"
    if not entry.get('author'):
        found_author = None
        if quote in QUOTE_MAP:
            found_author = QUOTE_MAP[quote]
        else:
            # Try partial match (key in quote)
            for k, v in QUOTE_MAP.items():
                if k in quote or quote in k:
                    found_author = v
                    break
        
        if found_author:
            entry['author'] = found_author
            updated_count += 1

with open('data/stoic-content.json', 'w') as f:
    json.dump(data, f, indent=2)

print(f"Updated {updated_count} entries with authors.")
